name: Build Artifact

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - dev

jobs:
    build:
        name: Build and Upload
        permissions:
            contents: read
            packages: read
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: "17"

            - name: Cache Gradle
              uses: burrunan/gradle-cache-action@v1

            - name: Build APK
              env:
                  ORG_GRADLE_PROJECT_githubPackagesUsername: ${{ github.actor }}
                  ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
              # Note: If your build normally requires signing to succeed, 
              # you may need to run 'assembleDebug' instead of 'assembleRelease'
              run: ./gradlew assembleRelease

            - name: Upload APK
              uses: actions/upload-artifact@v4
              with:
                  name: revanced-manager-apk
                  path: app/build/outputs/apk/release/*.apk
                  if-no-files-found: error
